/**
 * Rich detail for the 6 services in SERVICES_MENU.
 * Slugs must match slugify(SERVICES_MENU[].title):
 * graphic-creative-design, brand-identity-design, performance-marketing,
 * website-landing-page-development (website questionnaire), pitch-deck-corporate-decks, e-commerce-development.
 */
export const SERVICES_DETAIL = {
  "graphic-creative-design": {
    hero: {
      headline: "Graphic & Creative Design that captivates and converts",
      subheadline: "Professional visual content that elevates your brand and drives engagement",
      supportingText: "Based on 500+ successful design projects & 12 years of creative excellence",
      ctaText: "BOOK A CALL",
      ctaLink: "https://calendly.com/webfudgeagency",
    },
    stats: {
      projects: "500+",
      designs: "10K+",
      engagement: "85%",
      brandRecognition: "60%",
      conversionBoost: "45%",
      clientSatisfaction: "98%",
    },
    challenges: [
      {
        id: 1, title: "Inconsistent brand visuals",
        description: "Without cohesive visual design, your brand can appear unprofessional and fragmented. Consistent graphic design creates a unified brand identity that builds trust and recognition across all touchpoints.",
        icon: "https://cdn.lordicon.com/exymduqj.json"
      },
      {
        id: 2, title: "Low social media engagement",
        description: "Generic or poorly designed social media graphics fail to capture attention in crowded feeds. Eye-catching, well-designed creatives increase engagement rates and help your content stand out.",
        icon: "https://cdn.lordicon.com/lewtedlh.json"
      },
      {
        id: 3,
        title: "Ineffective marketing materials",
        description: "Weak visual design in marketing materials reduces their impact and conversion potential. Professional graphic design transforms your marketing assets into powerful tools that drive action.",
        icon: "https://cdn.lordicon.com/ijsqrapz.json"
      },
      { id: 4, title: "Outdated visual identity", description: "Using outdated design styles makes your brand appear behind the times. Modern, fresh graphic design keeps your brand relevant and appealing to contemporary audiences.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 5, title: "Lack of visual storytelling", description: "Without compelling visuals, your message may get lost. Creative design helps tell your brand's story visually, making complex ideas accessible and memorable.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
      { id: 6, title: "Time-consuming design creation", description: "Creating professional graphics in-house can be time-consuming and may lack the polish needed. Professional graphic design services deliver high-quality visuals efficiently, freeing your team to focus on core business.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
    ],
    process: [
      { step: 1, title: "Creative Brief & Discovery", description: "We begin by understanding your brand, target audience, and design objectives. Through detailed discussions, we gather insights to create designs that align with your goals and resonate with your audience." },
      { step: 2, title: "Concept Development", description: "Our creative team develops multiple design concepts and directions. We explore different visual styles, color palettes, and layouts to find the perfect approach for your project." },
      { step: 3, title: "Design Refinement", description: "Based on your feedback, we refine and polish the selected concepts. We pay attention to every detail, ensuring typography, spacing, and visual hierarchy work together harmoniously." },
      { step: 4, title: "Asset Creation & Optimization", description: "We create final design assets optimized for their intended use—whether for print, web, or social media. All files are delivered in the formats you need, ready for immediate use." },
      { step: 5, title: "Delivery & Brand Guidelines", description: "We deliver all final assets along with brand guidelines to ensure consistency. This helps maintain your visual identity across all future applications and touchpoints." },
    ],
    reasons: [
      { id: 1, title: "Expert creative team", description: "Our skilled designers bring years of experience and fresh perspectives to every project, ensuring your visuals are both professional and innovative.", icon: "https://cdn.lordicon.com/kdduutaw.json" },
      { id: 2, title: "Brand-consistent designs", description: "We ensure all designs align with your brand identity, creating cohesive visuals that strengthen brand recognition and trust.", icon: "https://cdn.lordicon.com/mypatlef.json" },
      {
        id: 3, title: "Multi-format expertise", description: "From social media graphics to print materials, we create designs optimized for any platform or medium you need.",
        icon: "https://cdn.lordicon.com/lksszjsn.json"
      },
      { id: 4, title: "Fast turnaround times", description: "Our efficient workflow and dedicated team ensure quick delivery without compromising on quality or creativity.", icon: "https://cdn.lordicon.com/warimioc.json" },
      { id: 5, title: "Data-driven creative decisions", description: "We combine creative excellence with performance insights to create designs that not only look great but also drive results.", icon: "https://cdn.lordicon.com/lhjwpfnn.json" },
      { id: 6, title: "Scalable design solutions", description: "We create design systems and templates that can scale with your business, making future design needs more efficient and cost-effective.", icon: "https://cdn.lordicon.com/tzfvcoue.json" },
    ],
    faqs: [
      { id: 1, question: "What types of graphic design services do you offer?", answer: "We offer comprehensive graphic design services including social media graphics, marketing banners, print materials, custom illustrations, infographics, brand collateral, and more. Our team can handle any visual design need for your business." },
      { id: 2, question: "How long does a graphic design project typically take?", answer: "Project timelines vary based on scope and complexity. Simple social media graphics might take a few days, while comprehensive brand identity packages may take several weeks. We'll provide a detailed timeline during our initial consultation based on your specific needs." },
      { id: 3, question: "Can you work with our existing brand guidelines?", answer: "Absolutely! We can work within your existing brand guidelines to ensure all new designs maintain consistency with your current brand identity. We can also help refine and expand your brand guidelines if needed." },
      { id: 4, question: "What file formats will I receive?", answer: "We deliver all final designs in the formats you need—whether that's high-resolution files for print, web-optimized formats, or source files for future edits. Common formats include PNG, JPG, PDF, SVG, and editable source files." },
      { id: 5, question: "Do you offer ongoing design support?", answer: "Yes, we offer ongoing design support and retainer packages for businesses that need regular design work. This ensures consistent quality and faster turnaround times for recurring design needs." },
      { id: 6, question: "How do you ensure designs are on-brand and effective?", answer: "We start every project with a thorough understanding of your brand, audience, and objectives. Our design process includes research, concept development, and iterative refinement to ensure designs are both on-brand and strategically effective." },
    ],
    relatedServices: ["graphics-design"],
  },

  "brand-identity-design": {
    hero: {
      headline: "Brand Identity Design that defines and differentiates your business",
      subheadline: "Complete brand systems that build recognition, trust, and lasting connections",
      supportingText: "Based on 500+ successful brand transformations & 12 years of brand expertise",
      ctaText: "BOOK A CALL",
      ctaLink: "https://calendly.com/webfudgeagency",
    },
    stats: {
      projects: "500+",
      brands: "400+",
      recognition: "70%",
      trust: "65%",
      marketPosition: "55%",
      clientSatisfaction: "98%",
    },
    challenges: [
      { id: 1, title: "Weak brand recognition", description: "Without a strong, consistent brand identity, your business struggles to stand out in a crowded market. A well-designed brand identity creates memorable visual elements that customers instantly recognize and trust.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
      { id: 2, title: "Inconsistent brand application", description: "Using different logos, colors, and styles across platforms confuses customers and weakens your brand. A comprehensive brand system ensures consistent application everywhere your brand appears.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 3, title: "Outdated brand image", description: "An outdated brand identity can make your business appear behind the times, even if your products or services are modern. Refreshing your brand identity keeps you relevant and appealing to current audiences.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 4, title: "Lack of brand differentiation", description: "If your brand looks similar to competitors, you miss opportunities to stand out. A unique brand identity helps you differentiate and communicate what makes your business special.", icon: "https://cdn.lordicon.com/exymduqj.json" },
      { id: 5, title: "Unclear brand values", description: "Without a cohesive brand identity, it's difficult to communicate your company's values and personality. Strategic brand design visually expresses who you are and what you stand for.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 6, title: "Fragmented brand experience", description: "Inconsistent branding across touchpoints creates a fragmented customer experience. A unified brand identity ensures every interaction reinforces your brand message and values.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
    ],
    process: [
      { step: 1, title: "Brand Discovery & Strategy", description: "We conduct in-depth research into your business, market, competitors, and target audience. Through workshops and analysis, we define your brand positioning, values, and personality to guide the design process." },
      { step: 2, title: "Logo Design & Concept Development", description: "We create multiple logo concepts that reflect your brand essence. Each concept explores different visual directions, from minimalist to expressive, ensuring we find the perfect representation of your brand." },
      { step: 3, title: "Brand System Development", description: "We develop comprehensive brand systems including color palettes, typography, imagery styles, and design patterns. This creates a cohesive visual language that can be applied consistently across all touchpoints." },
      { step: 4, title: "Brand Guidelines Creation", description: "We create detailed brand guidelines that document how to use your brand identity correctly. This ensures consistency and empowers your team to apply the brand confidently across all applications." },
      { step: 5, title: "Asset Delivery & Implementation", description: "We deliver all brand assets in various formats and provide support for implementation. This includes logo files, color codes, font files, and examples of brand application across different mediums." },
    ],
    reasons: [
      { id: 1, title: "Strategic brand expertise", description: "Our team combines design excellence with strategic thinking, ensuring your brand identity not only looks great but also supports your business objectives and market positioning.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
      { id: 2, title: "Comprehensive brand systems", description: "We don't just create logos—we build complete brand systems with guidelines, color palettes, typography, and application examples that ensure consistent brand expression.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 3, title: "Market research-driven design", description: "Every brand identity we create is informed by thorough market and competitor research, ensuring your brand stands out and resonates with your target audience.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 4, title: "Scalable brand solutions", description: "We design brand identities that work across all platforms and scales—from business cards to billboards, digital to print—ensuring your brand looks great everywhere.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
      { id: 5, title: "Long-term brand value", description: "A well-designed brand identity is an investment that pays dividends over time, building recognition, trust, and customer loyalty that drives business growth.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 6, title: "Ongoing brand support", description: "We provide brand guidelines and ongoing support to help you maintain brand consistency as your business grows and evolves.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
    ],
    faqs: [
      { id: 1, question: "What's included in a brand identity design package?", answer: "A comprehensive brand identity package typically includes logo design (multiple variations), color palette, typography selection, brand guidelines document, and examples of brand application. We can customize packages based on your specific needs and budget." },
      { id: 2, question: "How long does a brand identity project take?", answer: "Brand identity projects typically take 4-8 weeks, depending on complexity and the number of revisions. This includes research, concept development, refinement, and final delivery. We'll provide a detailed timeline during our initial consultation." },
      { id: 3, question: "Can you refresh an existing brand identity?", answer: "Absolutely! We can refresh and modernize existing brand identities while maintaining brand recognition. We'll analyze your current brand, identify areas for improvement, and evolve it to better reflect your current positioning and appeal to modern audiences." },
      { id: 4, question: "What if I need multiple logo variations?", answer: "We typically include multiple logo variations in our brand identity packages—such as horizontal, vertical, icon-only, and wordmark versions. This ensures your logo works effectively across different applications and spaces." },
      { id: 5, question: "Will I own the brand identity after completion?", answer: "Yes, once the project is complete and final payment is received, you own all rights to your brand identity. We'll provide all source files and documentation for your use." },
      { id: 6, question: "How do you ensure the brand identity reflects our company values?", answer: "We start every project with extensive discovery sessions to understand your company's values, mission, culture, and target audience. This deep understanding informs every design decision, ensuring your brand identity authentically represents who you are." },
    ],
    relatedServices: ["logo-design", "branding", "brand-identity"],
    /** Deep link for the discovery form (see BrandingQuestionnaire). */
    questionnairePath: "/services/branding/questionnaire",
  },

  "performance-marketing": {
    hero: {
      headline: "Performance marketing that drives real revenue not just clicks",
      subheadline: "Paid search, paid social, and full-funnel campaigns built for clarity, attribution, and ROI.",
      supportingText: "Based on 500+ growth engagements & 12 years of media and conversion experience",
      ctaText: "BOOK A CALL",
      ctaLink: "https://calendly.com/webfudgeagency",
    },
    stats: {
      projects: "500+",
      campaigns: "1K+",
      avgRoas: "3.2x",
      cplImprovement: "35%",
      conversionLift: "28%",
      clientSatisfaction: "98%",
    },
    challenges: [
      { id: 1, title: "Rising CAC and unclear ROI", description: "Without tight tracking and structured campaigns, cost per lead creeps up and leadership loses confidence in marketing. Performance marketing aligns spend to outcomes you can prove.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 2, title: "Weak attribution and reporting", description: "If you cannot see which channels and creatives drive pipeline, you cannot scale what works. We implement measurement frameworks so decisions are based on data, not guesses.", icon: "https://cdn.lordicon.com/lhjwpfnn.json" },
      { id: 3, title: "Traffic that does not convert", description: "High impressions and clicks mean little if landing pages and offers do not match intent. We align messaging, creative, and post-click experience to improve conversion rates.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 4, title: "Creative fatigue and stale messaging", description: "Audiences tune out repetitive ads. Structured testing of hooks, formats, and angles keeps campaigns fresh and sustains performance over time.", icon: "https://cdn.lordicon.com/exymduqj.json" },
      { id: 5, title: "Under-scaled winning campaigns", description: "Teams often pause winners too early or scale losers too fast. We use guardrails and incrementality thinking so budget moves toward what actually drives revenue.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
      { id: 6, title: "Siloed channels and inconsistent funnels", description: "When search, social, and site experience tell different stories, prospects drop off. We orchestrate a coherent funnel from first touch to qualified lead or sale.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
    ],
    process: [
      { step: 1, title: "Goals, ICP & offer mapping", description: "We clarify targets, ideal customer profiles, and what a qualified lead or sale looks like. That defines how we structure campaigns, bids, and creative." },
      { step: 2, title: "Measurement & tracking setup", description: "We audit tags, conversions, and CRM handoff so you can attribute results to channels and campaigns. Clean data is the foundation of performance work." },
      { step: 3, title: "Channel strategy & campaign build", description: "We design account and campaign structures for Google, Meta, LinkedIn, or other fits for your market—focused on intent, budget efficiency, and scale." },
      { step: 4, title: "Creative, copy & landing alignment", description: "We develop and test ads and landing experiences that match search terms and audience segments, reducing waste and improving conversion." },
      { step: 5, title: "Optimize, scale & report", description: "We run structured experiments, reallocate budget to winners, and deliver clear reporting on cost, volume, and pipeline impact so stakeholders see the story." },
    ],
    reasons: [
      { id: 1, title: "Full-funnel thinking", description: "We connect awareness, consideration, and conversion so media spend supports revenue—not vanity metrics.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
      { id: 2, title: "Platform depth", description: "Hands-on expertise across major ad platforms and formats, tuned to B2B and high-consideration journeys.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 3, title: "Creative testing discipline", description: "Systematic testing of messaging and creative so you learn what resonates and keep performance from stalling.", icon: "https://cdn.lordicon.com/exymduqj.json" },
      { id: 4, title: "CRO-aware campaigns", description: "We coordinate ads with landing pages and forms so traffic you pay for has a clear path to convert.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 5, title: "Transparent reporting", description: "Dashboards and readouts tied to your definitions of success—leads, SQLs, revenue, or ROAS—so finance and leadership stay aligned.", icon: "https://cdn.lordicon.com/lhjwpfnn.json" },
      { id: 6, title: "Continuous optimization", description: "Markets and auctions shift weekly; we monitor, adjust, and document changes so gains compound instead of eroding.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
    ],
    faqs: [
      { id: 1, question: "How much does performance marketing management cost?", answer: "Investment depends on ad spend, number of channels, creative volume, and reporting depth. After a short discovery, Webfudge proposes a clear scope—media management, creative production, and measurement—so you know fees and expected effort before you commit." },
      { id: 2, question: "How long until we see results?", answer: "Learning phases vary by channel and competition. Many accounts show directional improvement within weeks; mature optimization and stable CPL or ROAS often take a few months of structured testing. We set expectations up front and review progress on a regular cadence." },
      { id: 3, question: "Which channels do you run?", answer: "We commonly manage Google Ads, Meta, and LinkedIn for B2B, and add or prioritize channels based on your buyers and economics. The mix is always tied to where your ICP actually spends attention and budget." },
      { id: 4, question: "Do you only manage ads, or also landing pages?", answer: "Performance improves when ad promise and post-click experience match. We collaborate on landing page and form recommendations—often alongside your site or dev team—and can scope CRO tests where it moves the needle." },
      { id: 5, question: "How do you report on success?", answer: "We align on primary KPIs (leads, SQLs, pipeline, revenue, or ROAS) and build reporting that ties platform data to your CRM where possible. You get honest readouts, not cherry-picked screenshots." },
      { id: 6, question: "Can you audit our existing ad accounts?", answer: "Yes. An account and tracking audit is a strong starting point to find waste, structural issues, and quick wins before scaling spend." },
    ],
    relatedServices: ["website-landing-page-development", "graphic-creative-design", "brand-identity-design"],
  },

  "website-landing-page-development": {
    hero: {
      headline: "Website & Landing Page Design that converts visitors into customers",
      subheadline: "Strategic design that combines aesthetics with conversion optimization",
      supportingText: "Based on 500+ successful website designs & 12 years of digital expertise",
      ctaText: "BOOK A CALL",
      ctaLink: "https://calendly.com/webfudgeagency",
    },
    stats: {
      projects: "500+",
      conversions: "45%",
      engagement: "80%",
      loadSpeed: "2.5s",
      mobileOptimized: "100%",
      clientSatisfaction: "98%",
    },
    challenges: [
      { id: 1, title: "Low conversion rates", description: "Poorly designed websites and landing pages fail to convert visitors into customers. Strategic design with conversion-focused layouts and clear calls-to-action significantly improves conversion rates.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 2, title: "Poor mobile experience", description: "Websites that aren't optimized for mobile devices lose a significant portion of potential customers. Responsive design ensures your site looks and works perfectly on all devices.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 3, title: "Confusing navigation and structure", description: "Complex or unclear website structure frustrates visitors and increases bounce rates. Intuitive design with clear navigation helps users find what they need quickly and easily.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
      { id: 4, title: "Outdated visual design", description: "Dated website designs make your business appear unprofessional and behind the times. Modern, fresh designs build trust and keep visitors engaged with your brand.", icon: "https://cdn.lordicon.com/exymduqj.json" },
      { id: 5, title: "Weak landing page performance", description: "Landing pages that don't clearly communicate value or guide visitors to action waste marketing spend. Conversion-optimized landing page design maximizes ROI on your marketing campaigns.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 6, title: "Slow page load times", description: "Heavy, unoptimized designs lead to slow loading times that drive visitors away. We design with performance in mind, ensuring fast load times without sacrificing visual appeal.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
    ],
    process: [
      { step: 1, title: "Discovery & Strategy", description: "We analyze your business goals, target audience, and competitive landscape. Through research and strategy sessions, we define the design direction that will best serve your objectives and users." },
      { step: 2, title: "Information Architecture & Wireframes", description: "We create site maps and wireframes that establish the structure, navigation, and content hierarchy. This foundation ensures intuitive user flow and optimal conversion paths." },
      { step: 3, title: "Visual Design & Mockups", description: "We transform wireframes into high-fidelity designs with attention to typography, color, imagery, and layout. Every element is designed to guide users toward your goals while creating an engaging experience." },
      { step: 4, title: "Responsive Design Development", description: "We ensure designs work beautifully across all devices—desktop, tablet, and mobile. Responsive layouts adapt seamlessly to different screen sizes while maintaining design integrity." },
      { step: 5, title: "Design Handoff & Documentation", description: "We prepare comprehensive design files, style guides, and specifications for seamless handoff to development. This ensures your website is built exactly as designed." },
    ],
    reasons: [
      { id: 1, title: "Conversion-focused design", description: "Every design decision is made with conversion goals in mind. We create layouts, CTAs, and user flows that guide visitors toward taking action and becoming customers.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 2, title: "Fully responsive designs", description: "All our designs are mobile-first and fully responsive, ensuring your website provides an excellent experience on every device and screen size.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 3, title: "User-centered approach", description: "We design with your users in mind, creating intuitive navigation and clear information hierarchy that makes it easy for visitors to find what they need and take action.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 4, title: "Performance-optimized", description: "We design with performance in mind, ensuring fast load times and smooth interactions that keep visitors engaged and improve search engine rankings.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 5, title: "Modern, professional aesthetics", description: "Our designs combine current design trends with timeless principles, creating websites that look professional, modern, and trustworthy.", icon: "https://cdn.lordicon.com/exymduqj.json" },
      { id: 6, title: "Comprehensive design systems", description: "We create complete design systems with component libraries and style guides, making it easy to maintain consistency and scale your website over time.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
    ],
    faqs: [
      { id: 1, question: "What's the difference between website design and landing page design?", answer: "Website design focuses on creating complete, multi-page sites with navigation and various sections. Landing page design focuses on single-page experiences optimized for specific marketing campaigns with clear conversion goals. We excel at both." },
      { id: 2, question: "How long does a website or landing page design project take?", answer: "Timelines vary based on scope and complexity. A simple landing page might take 2-3 weeks, while a full website design could take 4-8 weeks. We'll provide a detailed timeline during our initial consultation based on your specific needs." },
      { id: 3, question: "Will my design be mobile-responsive?", answer: "Absolutely! All our designs are mobile-first and fully responsive. We ensure your website or landing page looks and works perfectly on desktop, tablet, and mobile devices." },
      { id: 4, question: "Do you design for specific platforms (WordPress, Shopify, etc.)?", answer: "Yes, we can design for any platform including WordPress, Shopify, Webflow, custom development, and more. We'll adapt our design approach to work seamlessly with your chosen platform." },
      { id: 5, question: "What deliverables will I receive?", answer: "You'll receive high-fidelity design mockups, responsive designs for different screen sizes, design specifications, style guides, and all necessary assets. We prepare everything needed for seamless development handoff." },
      { id: 6, question: "Can you help improve conversion rates on existing pages?", answer: "Yes! We can audit your existing pages and redesign them with conversion optimization in mind. We'll identify barriers to conversion and create designs that guide visitors more effectively toward your goals." },
    ],
    relatedServices: ["website-development"],
    questionnairePath: "/services/website/questionnaire",
  },

  "pitch-deck-corporate-decks": {
    hero: {
      headline: "Pitch Deck & Corporate Decks that communicate value clearly",
      subheadline: "Custom investor and corporate decks designed to communicate value clearly",
      supportingText: "Based on 500+ successful decks & 12 years of presentation design expertise",
      ctaText: "BOOK A CALL",
      ctaLink: "https://calendly.com/webfudgeagency",
    },
    stats: {
      projects: "500+",
      decks: "1K+",
      fundsRaised: "$100M+",
      clientSatisfaction: "98%",
      turnaround: "2 weeks",
    },
    challenges: [
      { id: 1, title: "Weak investor presentations", description: "Generic or poorly designed pitch decks fail to capture investor attention. Professional deck design clarifies your story and differentiates you in competitive fundraising.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 2, title: "Inconsistent corporate materials", description: "Inconsistent presentation design across teams weakens your brand. We create cohesive deck templates and guidelines for consistent, professional communication.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 3, title: "Data-heavy slides that confuse", description: "Dense, unclear data visualisation loses your audience. We transform complex information into clear, compelling visuals that support your narrative.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 4, title: "Outdated design and narrative", description: "Outdated deck design and structure can undermine your credibility. We modernize content and design so your story lands with impact.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 5, title: "No clear narrative arc", description: "Decks that jump between topics lose the audience. We structure your deck with a clear narrative that builds to a compelling ask.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
      { id: 6, title: "Time-consuming in-house design", description: "Creating investor-grade decks in-house is time-consuming. We deliver polished, on-brand decks so you can focus on fundraising and execution.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
    ],
    process: [
      { step: 1, title: "Brief & Story Outline", description: "We align on your narrative, key messages, and audience. We outline the deck structure and flow so every slide supports your story and ask." },
      { step: 2, title: "Content & Data Visualisation", description: "We turn your content and data into clear, impactful visuals. We design charts, tables, and diagrams that are easy to scan and remember." },
      { step: 3, title: "Design & Visual Refinement", description: "We apply a consistent visual system—typography, color, imagery—so the deck feels professional and on-brand. We refine based on your feedback." },
      { step: 4, title: "Speaker Notes & Handouts", description: "We add speaker notes and prepare handout or PDF versions as needed, so you can present and share the deck with confidence." },
      { step: 5, title: "Delivery & Revisions", description: "We deliver final files in the formats you need (PPT, Keynote, PDF) and support a round of revisions so the deck is pitch-ready." },
    ],
    reasons: [
      { id: 1, title: "Investor-ready design", description: "We design decks that meet the expectations of investors and boards, with clear narrative and professional visuals.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
      { id: 2, title: "Data visualisation expertise", description: "We turn complex data into clear charts and visuals that support your story and make key points memorable.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 3, title: "Consistent brand application", description: "We apply your brand guidelines across every slide so your deck reinforces your identity and credibility.", icon: "https://cdn.lordicon.com/exymduqj.json" },
      { id: 4, title: "Fast turnaround", description: "We work to your timeline so you can hit fundraising and presentation deadlines without sacrificing quality.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 5, title: "Narrative and structure", description: "We focus on story and flow, not just aesthetics, so your deck builds to a clear, compelling ask.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
      { id: 6, title: "Multiple formats", description: "We deliver in PowerPoint, Keynote, and PDF, with speaker notes and handout versions as needed.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
    ],
    faqs: [
      { id: 1, question: "What's included in a pitch deck design?", answer: "We typically include a full deck structure, slide design, data visualisation, and narrative flow. We can work from your outline or help you develop the story from scratch. Final files are delivered in your preferred format (PPT, Keynote, PDF)." },
      { id: 2, question: "How long does a pitch deck project take?", answer: "Timelines vary with scope. A standard investor deck often takes 2–3 weeks from brief to final delivery. We can accommodate faster turnarounds when needed." },
      { id: 3, question: "Can you work with our existing deck?", answer: "Yes. We can redesign an existing deck, improve narrative and data slides, and align the design with your brand." },
      { id: 4, question: "Do you design for both pitch and corporate decks?", answer: "Yes. We design investor pitch decks, board decks, sales decks, and internal corporate presentations. We adapt structure and tone to the audience and goal." },
      { id: 5, question: "What if we need last-minute changes?", answer: "We include a round of revisions in our process and can accommodate urgent changes when possible. For ongoing needs, we can discuss retainer support." },
      { id: 6, question: "Will the deck match our brand?", answer: "We use your brand guidelines—colors, fonts, logo—so the deck is consistent with your other materials and reinforces your brand." },
    ],
    relatedServices: ["pitch-deck-design", "corporate-presentations"],
  },

  "e-commerce-development": {
    hero: {
      headline: "E-commerce Development that drives sales and grows your online business",
      subheadline: "Powerful online stores built for conversion and scalability",
      supportingText: "Based on 500+ successful e-commerce projects & 12 years of online retail expertise",
      ctaText: "BOOK A CALL",
      ctaLink: "https://calendly.com/webfudgeagency",
    },
    stats: {
      projects: "500+",
      conversionRate: "3.5%",
      revenue: "$50M+",
      loadSpeed: "<2s",
      mobileOptimized: "100%",
      clientSatisfaction: "98%",
    },
    challenges: [
      { id: 1, title: "Low conversion rates", description: "Poorly designed checkout processes and confusing navigation lead to abandoned carts. We build e-commerce sites optimized for conversion with streamlined checkout and clear product presentation.", icon: "https://cdn.lordicon.com/slkvcfos.json" },
      { id: 2, title: "Limited payment options", description: "Limited payment methods can lose sales. We integrate multiple payment gateways and options to give customers flexibility and increase conversion rates.", icon: "https://cdn.lordicon.com/gqzfzudq.json" },
      { id: 3, title: "Poor mobile shopping experience", description: "E-commerce sites that don't work well on mobile lose significant sales. We build mobile-optimized stores that provide excellent shopping experiences on all devices.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 4, title: "Inventory management complexity", description: "Managing inventory, orders, and products across multiple channels is challenging. We build or integrate systems that streamline inventory management and order processing.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 5, title: "Slow page load times", description: "Slow-loading product pages and checkout processes drive customers away. We optimize for speed, ensuring fast load times that keep customers engaged.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 6, title: "Limited scalability", description: "E-commerce platforms that can't handle growth limit your business potential. We build scalable solutions that can grow with your business and handle traffic spikes.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
    ],
    process: [
      { step: 1, title: "E-commerce Strategy & Planning", description: "We analyze your products, target market, and business goals to define the e-commerce strategy. We select the best platform (Shopify, WooCommerce, or custom) and plan features that will drive sales." },
      { step: 2, title: "Design & User Experience", description: "We design intuitive product pages, shopping carts, and checkout flows optimized for conversion. Every element is designed to guide customers toward purchase while providing an excellent shopping experience." },
      { step: 3, title: "Development & Integration", description: "We build your online store, integrate payment gateways, shipping providers, inventory systems, and third-party tools. We ensure all features work seamlessly together." },
      { step: 4, title: "Product Setup & Configuration", description: "We set up your product catalog, configure shipping options, tax settings, and payment methods. We ensure your store is ready to accept orders and process transactions." },
      { step: 5, title: "Testing & Launch", description: "We thoroughly test all functionality including checkout, payments, inventory, and integrations. We handle launch procedures and provide training to ensure your team can manage the store effectively." },
    ],
    reasons: [
      { id: 1, title: "Conversion-optimized design", description: "We design every element with conversion in mind—from product pages to checkout—creating a shopping experience that guides customers to purchase and maximizes sales.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 2, title: "Multiple platform expertise", description: "We're experts in Shopify, WooCommerce, and custom e-commerce development, selecting the best platform for your specific needs, budget, and growth plans.", icon: "https://cdn.lordicon.com/slkvcfos.json" },
      { id: 3, title: "Payment & shipping integration", description: "We integrate multiple payment gateways and shipping providers, giving customers flexibility and ensuring smooth order processing and fulfillment.", icon: "https://cdn.lordicon.com/gqzfzudq.json" },
      { id: 4, title: "Mobile-optimized shopping", description: "We build mobile-first e-commerce experiences that make shopping easy on any device, capturing the growing mobile commerce market.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 5, title: "Scalable architecture", description: "We build e-commerce solutions that can scale with your business, handling increased traffic, products, and orders as you grow.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
      { id: 6, title: "Ongoing support & optimization", description: "We provide ongoing support, updates, and optimization to ensure your store continues to perform well and adapt to changing market needs.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
    ],
    faqs: [
      { id: 1, question: "Which e-commerce platform should I choose?", answer: "The best platform depends on your needs. Shopify is great for quick setup and ease of use. WooCommerce offers more customization for WordPress users. Custom solutions provide maximum flexibility. We'll recommend the best option based on your requirements." },
      { id: 2, question: "How long does an e-commerce development project take?", answer: "Timelines vary based on platform and complexity. A Shopify store might take 4-6 weeks, while a custom e-commerce solution could take 8-12 weeks or more. We'll provide a detailed timeline during our consultation." },
      { id: 3, question: "Can you integrate with our existing systems?", answer: "Yes! We can integrate your e-commerce store with inventory management systems, ERPs, CRMs, email marketing tools, accounting software, and more. We ensure seamless data flow across your business systems." },
      { id: 4, question: "What payment methods can you integrate?", answer: "We can integrate various payment gateways including Stripe, PayPal, Square, Authorize.Net, and many others. We'll set up the payment methods that work best for your business and customers." },
      { id: 5, question: "Will my store be mobile-responsive?", answer: "Absolutely! All e-commerce stores we build are fully responsive and mobile-optimized. We ensure your store provides an excellent shopping experience on desktop, tablet, and mobile devices." },
      { id: 6, question: "Do you provide training and ongoing support?", answer: "Yes! We provide comprehensive training on managing products, orders, and store settings. We also offer ongoing support packages for updates, maintenance, and optimization." },
    ],
    relatedServices: ["ecommerce-development"],
  },
};
