/**
 * Rich detail for the 6 services in SERVICES_MENU.
 * Slugs must match slugify(SERVICES_MENU[].title):
 * graphic-creative-design, brand-identity-design, uiux-design,
 * website-landing-page-development, pitch-deck-corporate-decks, e-commerce-development.
 */
export const SERVICES_DETAIL = {
  "graphic-creative-design": {
    hero: {
      headline: "Graphic & Creative Design that captivates and converts",
      subheadline: "Professional visual content that elevates your brand and drives engagement",
      supportingText: "Based on 500+ successful design projects & 12 years of creative excellence",
      ctaText: "BOOK A CALL",
      ctaLink: "https://calendly.com/webfudgeagency",
    },
    stats: {
      projects: "500+",
      designs: "10K+",
      engagement: "85%",
      brandRecognition: "60%",
      conversionBoost: "45%",
      clientSatisfaction: "98%",
    },
    challenges: [
      {
        id: 1, title: "Inconsistent brand visuals",
        description: "Without cohesive visual design, your brand can appear unprofessional and fragmented. Consistent graphic design creates a unified brand identity that builds trust and recognition across all touchpoints.",
        icon: "https://cdn.lordicon.com/exymduqj.json"
      },
      {
        id: 2, title: "Low social media engagement",
        description: "Generic or poorly designed social media graphics fail to capture attention in crowded feeds. Eye-catching, well-designed creatives increase engagement rates and help your content stand out.",
        icon: "https://cdn.lordicon.com/lewtedlh.json"
      },
      {
        id: 3,
        title: "Ineffective marketing materials",
        description: "Weak visual design in marketing materials reduces their impact and conversion potential. Professional graphic design transforms your marketing assets into powerful tools that drive action.",
        icon: "https://cdn.lordicon.com/ijsqrapz.json"
      },
      { id: 4, title: "Outdated visual identity", description: "Using outdated design styles makes your brand appear behind the times. Modern, fresh graphic design keeps your brand relevant and appealing to contemporary audiences.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 5, title: "Lack of visual storytelling", description: "Without compelling visuals, your message may get lost. Creative design helps tell your brand's story visually, making complex ideas accessible and memorable.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
      { id: 6, title: "Time-consuming design creation", description: "Creating professional graphics in-house can be time-consuming and may lack the polish needed. Professional graphic design services deliver high-quality visuals efficiently, freeing your team to focus on core business.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
    ],
    process: [
      { step: 1, title: "Creative Brief & Discovery", description: "We begin by understanding your brand, target audience, and design objectives. Through detailed discussions, we gather insights to create designs that align with your goals and resonate with your audience." },
      { step: 2, title: "Concept Development", description: "Our creative team develops multiple design concepts and directions. We explore different visual styles, color palettes, and layouts to find the perfect approach for your project." },
      { step: 3, title: "Design Refinement", description: "Based on your feedback, we refine and polish the selected concepts. We pay attention to every detail, ensuring typography, spacing, and visual hierarchy work together harmoniously." },
      { step: 4, title: "Asset Creation & Optimization", description: "We create final design assets optimized for their intended use—whether for print, web, or social media. All files are delivered in the formats you need, ready for immediate use." },
      { step: 5, title: "Delivery & Brand Guidelines", description: "We deliver all final assets along with brand guidelines to ensure consistency. This helps maintain your visual identity across all future applications and touchpoints." },
    ],
    reasons: [
      { id: 1, title: "Expert creative team", description: "Our skilled designers bring years of experience and fresh perspectives to every project, ensuring your visuals are both professional and innovative.", icon: "https://cdn.lordicon.com/kdduutaw.json" },
      { id: 2, title: "Brand-consistent designs", description: "We ensure all designs align with your brand identity, creating cohesive visuals that strengthen brand recognition and trust.", icon: "https://cdn.lordicon.com/mypatlef.json" },
      {
        id: 3, title: "Multi-format expertise", description: "From social media graphics to print materials, we create designs optimized for any platform or medium you need.",
        icon: "https://cdn.lordicon.com/lksszjsn.json"
      },
      { id: 4, title: "Fast turnaround times", description: "Our efficient workflow and dedicated team ensure quick delivery without compromising on quality or creativity.", icon: "https://cdn.lordicon.com/warimioc.json" },
      { id: 5, title: "Data-driven creative decisions", description: "We combine creative excellence with performance insights to create designs that not only look great but also drive results.", icon: "https://cdn.lordicon.com/lhjwpfnn.json" },
      { id: 6, title: "Scalable design solutions", description: "We create design systems and templates that can scale with your business, making future design needs more efficient and cost-effective.", icon: "https://cdn.lordicon.com/tzfvcoue.json" },
    ],
    faqs: [
      { id: 1, question: "What types of graphic design services do you offer?", answer: "We offer comprehensive graphic design services including social media graphics, marketing banners, print materials, custom illustrations, infographics, brand collateral, and more. Our team can handle any visual design need for your business." },
      { id: 2, question: "How long does a graphic design project typically take?", answer: "Project timelines vary based on scope and complexity. Simple social media graphics might take a few days, while comprehensive brand identity packages may take several weeks. We'll provide a detailed timeline during our initial consultation based on your specific needs." },
      { id: 3, question: "Can you work with our existing brand guidelines?", answer: "Absolutely! We can work within your existing brand guidelines to ensure all new designs maintain consistency with your current brand identity. We can also help refine and expand your brand guidelines if needed." },
      { id: 4, question: "What file formats will I receive?", answer: "We deliver all final designs in the formats you need—whether that's high-resolution files for print, web-optimized formats, or source files for future edits. Common formats include PNG, JPG, PDF, SVG, and editable source files." },
      { id: 5, question: "Do you offer ongoing design support?", answer: "Yes, we offer ongoing design support and retainer packages for businesses that need regular design work. This ensures consistent quality and faster turnaround times for recurring design needs." },
      { id: 6, question: "How do you ensure designs are on-brand and effective?", answer: "We start every project with a thorough understanding of your brand, audience, and objectives. Our design process includes research, concept development, and iterative refinement to ensure designs are both on-brand and strategically effective." },
    ],
    relatedServices: ["graphics-design"],
  },

  "brand-identity-design": {
    hero: {
      headline: "Brand Identity Design that defines and differentiates your business",
      subheadline: "Complete brand systems that build recognition, trust, and lasting connections",
      supportingText: "Based on 500+ successful brand transformations & 12 years of brand expertise",
      ctaText: "BOOK A CALL",
      ctaLink: "https://calendly.com/webfudgeagency",
    },
    stats: {
      projects: "500+",
      brands: "400+",
      recognition: "70%",
      trust: "65%",
      marketPosition: "55%",
      clientSatisfaction: "98%",
    },
    challenges: [
      { id: 1, title: "Weak brand recognition", description: "Without a strong, consistent brand identity, your business struggles to stand out in a crowded market. A well-designed brand identity creates memorable visual elements that customers instantly recognize and trust.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
      { id: 2, title: "Inconsistent brand application", description: "Using different logos, colors, and styles across platforms confuses customers and weakens your brand. A comprehensive brand system ensures consistent application everywhere your brand appears.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 3, title: "Outdated brand image", description: "An outdated brand identity can make your business appear behind the times, even if your products or services are modern. Refreshing your brand identity keeps you relevant and appealing to current audiences.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 4, title: "Lack of brand differentiation", description: "If your brand looks similar to competitors, you miss opportunities to stand out. A unique brand identity helps you differentiate and communicate what makes your business special.", icon: "https://cdn.lordicon.com/exymduqj.json" },
      { id: 5, title: "Unclear brand values", description: "Without a cohesive brand identity, it's difficult to communicate your company's values and personality. Strategic brand design visually expresses who you are and what you stand for.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 6, title: "Fragmented brand experience", description: "Inconsistent branding across touchpoints creates a fragmented customer experience. A unified brand identity ensures every interaction reinforces your brand message and values.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
    ],
    process: [
      { step: 1, title: "Brand Discovery & Strategy", description: "We conduct in-depth research into your business, market, competitors, and target audience. Through workshops and analysis, we define your brand positioning, values, and personality to guide the design process." },
      { step: 2, title: "Logo Design & Concept Development", description: "We create multiple logo concepts that reflect your brand essence. Each concept explores different visual directions, from minimalist to expressive, ensuring we find the perfect representation of your brand." },
      { step: 3, title: "Brand System Development", description: "We develop comprehensive brand systems including color palettes, typography, imagery styles, and design patterns. This creates a cohesive visual language that can be applied consistently across all touchpoints." },
      { step: 4, title: "Brand Guidelines Creation", description: "We create detailed brand guidelines that document how to use your brand identity correctly. This ensures consistency and empowers your team to apply the brand confidently across all applications." },
      { step: 5, title: "Asset Delivery & Implementation", description: "We deliver all brand assets in various formats and provide support for implementation. This includes logo files, color codes, font files, and examples of brand application across different mediums." },
    ],
    reasons: [
      { id: 1, title: "Strategic brand expertise", description: "Our team combines design excellence with strategic thinking, ensuring your brand identity not only looks great but also supports your business objectives and market positioning.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
      { id: 2, title: "Comprehensive brand systems", description: "We don't just create logos—we build complete brand systems with guidelines, color palettes, typography, and application examples that ensure consistent brand expression.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 3, title: "Market research-driven design", description: "Every brand identity we create is informed by thorough market and competitor research, ensuring your brand stands out and resonates with your target audience.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 4, title: "Scalable brand solutions", description: "We design brand identities that work across all platforms and scales—from business cards to billboards, digital to print—ensuring your brand looks great everywhere.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
      { id: 5, title: "Long-term brand value", description: "A well-designed brand identity is an investment that pays dividends over time, building recognition, trust, and customer loyalty that drives business growth.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 6, title: "Ongoing brand support", description: "We provide brand guidelines and ongoing support to help you maintain brand consistency as your business grows and evolves.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
    ],
    faqs: [
      { id: 1, question: "What's included in a brand identity design package?", answer: "A comprehensive brand identity package typically includes logo design (multiple variations), color palette, typography selection, brand guidelines document, and examples of brand application. We can customize packages based on your specific needs and budget." },
      { id: 2, question: "How long does a brand identity project take?", answer: "Brand identity projects typically take 4-8 weeks, depending on complexity and the number of revisions. This includes research, concept development, refinement, and final delivery. We'll provide a detailed timeline during our initial consultation." },
      { id: 3, question: "Can you refresh an existing brand identity?", answer: "Absolutely! We can refresh and modernize existing brand identities while maintaining brand recognition. We'll analyze your current brand, identify areas for improvement, and evolve it to better reflect your current positioning and appeal to modern audiences." },
      { id: 4, question: "What if I need multiple logo variations?", answer: "We typically include multiple logo variations in our brand identity packages—such as horizontal, vertical, icon-only, and wordmark versions. This ensures your logo works effectively across different applications and spaces." },
      { id: 5, question: "Will I own the brand identity after completion?", answer: "Yes, once the project is complete and final payment is received, you own all rights to your brand identity. We'll provide all source files and documentation for your use." },
      { id: 6, question: "How do you ensure the brand identity reflects our company values?", answer: "We start every project with extensive discovery sessions to understand your company's values, mission, culture, and target audience. This deep understanding informs every design decision, ensuring your brand identity authentically represents who you are." },
    ],
    relatedServices: ["logo-design", "branding", "brand-identity"],
  },

  "uiux-design": {
    hero: {
      headline: "UI/UX design that gets your B2B product to market faster.",
      subheadline: "Our unique framework + AI tools deliver results 2x faster",
      supportingText: "Based on 500+ finished projects & 12 years of experience",
      ctaText: "BOOK A CALL",
      ctaLink: "https://calendly.com/webfudgeagency",
    },
    stats: {
      projects: "500+",
      users: "3.4M",
      fundsRaised: "$530M",
      launchSpeed: "40%",
      costReduction: "20%",
      scalingEfficiency: "25%",
    },
    challenges: [
      { id: 1, title: "Low user engagement", description: "Businesses struggle with low user engagement and high drop-off rates when their product feels confusing or frustrating to navigate. Taking care of UI/UX will help you deal with it, offering practical design solutions to make your users satisfied.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 2, title: "Design-driven overspending", description: "Effective design minimizes the risk of overspending on unnecessary features, bringing you closer to product-market fit. Investing in UI/UX design services ensures a user-centered design from the start.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 3, title: "Poor conversion rates", description: "If users find the product unappealing during the trial period, they are less likely to commit to a full purchase. In this case, improving UI/UX design can greatly impact on your conversion rates and make users take the desired actions.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 4, title: "Outdated design solutions", description: "Keeping your product current with modern UI/UX decisions improves user satisfaction. As design trends change, relying on outdated solutions can drag down your project's effectiveness and appeal.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 5, title: "Inefficient onboarding process", description: "No one likes to see a lot of questions and wonder which button to click to finally sign up. With simplified onboarding, you can make users engaged from the start, and that's where UI/UX design check can help.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
      { id: 6, title: "Low accessibility", description: "If your project has significant barriers for users with disabilities, many potential clients will simply drop off. Accessible UI/UX design creates an inclusive environment where all people can engage with your product.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
    ],
    process: [
      { step: 1, title: "Discovery & Strategy Planning", description: "We start by understanding your business goals, target audience, and market positioning. Through workshops and research, we develop a comprehensive strategy that aligns design with your objectives." },
      { step: 2, title: "Wireframes & Concepts", description: "Creating low-fidelity wireframes and concept designs to establish information architecture and user flows. This phase ensures the foundation is solid before visual design begins." },
      { step: 3, title: "UI Design & Visual Refinement", description: "Transforming wireframes into high-fidelity designs with attention to visual hierarchy, typography, color systems, and interaction patterns. Every pixel is crafted for optimal user experience." },
      { step: 4, title: "Development Preparation", description: "Preparing design files with detailed specifications, component libraries, and style guides. We ensure seamless handoff to development teams with organized assets and documentation." },
      { step: 5, title: "Testing & Validation", description: "Conducting usability testing and gathering feedback to refine designs. We validate solutions with real users to ensure the final product meets both business and user needs." },
    ],
    reasons: [
      { id: 1, title: "Team of 120 full-time professionals", description: "With 120 in-house experts, we manage projects efficiently and ensure high-quality results without relying on freelancers.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 2, title: "Data-driven decisions", description: "Every design decision is backed by user research and data, ensuring visually appealing designs that drive results.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
      { id: 3, title: "User-centered design for higher engagement", description: "We focus on users' needs, creating intuitive interfaces that boost engagement, retention, and seamless exploration.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 4, title: "Improved developer efficiency", description: "We deliver clear, well-documented designs to streamline development, reduce friction, and save your team time.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 5, title: "Customized solutions for your business goals", description: "We design solutions tailored to your product's needs and goals, focusing on boosting conversions and improving onboarding.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 6, title: "Ongoing optimization and support", description: "We design and continuously optimize, using real-time data and feedback to refine your product and meet evolving user needs.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
    ],
    faqs: [
      { id: 1, question: "How much does a UI/UX design project cost?", answer: "The cost of a UI/UX design project varies depending on factors like complexity, scope, and customization. After assessing your requirements, Webfudge provides a detailed proposal outlining the project's scope, timeline, and associated costs. Our goal is to balance transparent pricing with delivering high-quality solutions tailored to your unique business objectives." },
      { id: 2, question: "How long does a typical UI/UX design project take?", answer: "The duration of a UI/UX design project varies based on its scope and complexity. For example, smaller tasks like audits can be completed faster, while larger, more intricate projects may require more time. During our initial discussions, we'll provide a clear timeline tailored to your specific needs and objectives, keeping you informed at every step." },
      { id: 3, question: "What deliverables can I expect from a UI/UX design project?", answer: "At Webfudge, every project is tailored to your specific goals, ensuring you receive a comprehensive range of deliverables. These typically include user flows, wireframes, high-fidelity UI designs, interactive prototypes, and a cohesive design system or component library. We also provide finalized assets and documentation to ensure a seamless handoff to your development team." },
      { id: 4, question: "Do I need both UI and UX design services?", answer: "Yes, the UI (user interface) and UX (user experience) designs complement each other. While UX focuses on the structure and usability of your product, UI brings it to life with engaging visuals and interactions. At Webfudge, we combine both to create designs that are not only intuitive but also visually compelling." },
      { id: 5, question: "How can I enhance my existing product's UI/UX design?", answer: "If you're looking to improve your current product's user interface and experience, our UI/UX audit is an excellent starting point. We'll conduct a comprehensive analysis to identify areas for enhancement and provide actionable recommendations to elevate your product's design and usability." },
      { id: 6, question: "Will my design be fully responsive and ready for development?", answer: "Absolutely. At Webfudge, we make sure your design is optimized for all devices — desktop, tablet, and mobile — so users enjoy a consistent experience wherever they go. We also prepare every design for a seamless handoff to development, providing organized layers, labeled assets, and detailed design specifications." },
    ],
    relatedServices: ["uiux-design"],
  },

  "website-landing-page-development": {
    hero: {
      headline: "Website & Landing Page Design that converts visitors into customers",
      subheadline: "Strategic design that combines aesthetics with conversion optimization",
      supportingText: "Based on 500+ successful website designs & 12 years of digital expertise",
      ctaText: "BOOK A CALL",
      ctaLink: "https://calendly.com/webfudgeagency",
    },
    stats: {
      projects: "500+",
      conversions: "45%",
      engagement: "80%",
      loadSpeed: "2.5s",
      mobileOptimized: "100%",
      clientSatisfaction: "98%",
    },
    challenges: [
      { id: 1, title: "Low conversion rates", description: "Poorly designed websites and landing pages fail to convert visitors into customers. Strategic design with conversion-focused layouts and clear calls-to-action significantly improves conversion rates.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 2, title: "Poor mobile experience", description: "Websites that aren't optimized for mobile devices lose a significant portion of potential customers. Responsive design ensures your site looks and works perfectly on all devices.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 3, title: "Confusing navigation and structure", description: "Complex or unclear website structure frustrates visitors and increases bounce rates. Intuitive design with clear navigation helps users find what they need quickly and easily.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
      { id: 4, title: "Outdated visual design", description: "Dated website designs make your business appear unprofessional and behind the times. Modern, fresh designs build trust and keep visitors engaged with your brand.", icon: "https://cdn.lordicon.com/exymduqj.json" },
      { id: 5, title: "Weak landing page performance", description: "Landing pages that don't clearly communicate value or guide visitors to action waste marketing spend. Conversion-optimized landing page design maximizes ROI on your marketing campaigns.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 6, title: "Slow page load times", description: "Heavy, unoptimized designs lead to slow loading times that drive visitors away. We design with performance in mind, ensuring fast load times without sacrificing visual appeal.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
    ],
    process: [
      { step: 1, title: "Discovery & Strategy", description: "We analyze your business goals, target audience, and competitive landscape. Through research and strategy sessions, we define the design direction that will best serve your objectives and users." },
      { step: 2, title: "Information Architecture & Wireframes", description: "We create site maps and wireframes that establish the structure, navigation, and content hierarchy. This foundation ensures intuitive user flow and optimal conversion paths." },
      { step: 3, title: "Visual Design & Mockups", description: "We transform wireframes into high-fidelity designs with attention to typography, color, imagery, and layout. Every element is designed to guide users toward your goals while creating an engaging experience." },
      { step: 4, title: "Responsive Design Development", description: "We ensure designs work beautifully across all devices—desktop, tablet, and mobile. Responsive layouts adapt seamlessly to different screen sizes while maintaining design integrity." },
      { step: 5, title: "Design Handoff & Documentation", description: "We prepare comprehensive design files, style guides, and specifications for seamless handoff to development. This ensures your website is built exactly as designed." },
    ],
    reasons: [
      { id: 1, title: "Conversion-focused design", description: "Every design decision is made with conversion goals in mind. We create layouts, CTAs, and user flows that guide visitors toward taking action and becoming customers.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 2, title: "Fully responsive designs", description: "All our designs are mobile-first and fully responsive, ensuring your website provides an excellent experience on every device and screen size.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 3, title: "User-centered approach", description: "We design with your users in mind, creating intuitive navigation and clear information hierarchy that makes it easy for visitors to find what they need and take action.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 4, title: "Performance-optimized", description: "We design with performance in mind, ensuring fast load times and smooth interactions that keep visitors engaged and improve search engine rankings.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 5, title: "Modern, professional aesthetics", description: "Our designs combine current design trends with timeless principles, creating websites that look professional, modern, and trustworthy.", icon: "https://cdn.lordicon.com/exymduqj.json" },
      { id: 6, title: "Comprehensive design systems", description: "We create complete design systems with component libraries and style guides, making it easy to maintain consistency and scale your website over time.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
    ],
    faqs: [
      { id: 1, question: "What's the difference between website design and landing page design?", answer: "Website design focuses on creating complete, multi-page sites with navigation and various sections. Landing page design focuses on single-page experiences optimized for specific marketing campaigns with clear conversion goals. We excel at both." },
      { id: 2, question: "How long does a website or landing page design project take?", answer: "Timelines vary based on scope and complexity. A simple landing page might take 2-3 weeks, while a full website design could take 4-8 weeks. We'll provide a detailed timeline during our initial consultation based on your specific needs." },
      { id: 3, question: "Will my design be mobile-responsive?", answer: "Absolutely! All our designs are mobile-first and fully responsive. We ensure your website or landing page looks and works perfectly on desktop, tablet, and mobile devices." },
      { id: 4, question: "Do you design for specific platforms (WordPress, Shopify, etc.)?", answer: "Yes, we can design for any platform including WordPress, Shopify, Webflow, custom development, and more. We'll adapt our design approach to work seamlessly with your chosen platform." },
      { id: 5, question: "What deliverables will I receive?", answer: "You'll receive high-fidelity design mockups, responsive designs for different screen sizes, design specifications, style guides, and all necessary assets. We prepare everything needed for seamless development handoff." },
      { id: 6, question: "Can you help improve conversion rates on existing pages?", answer: "Yes! We can audit your existing pages and redesign them with conversion optimization in mind. We'll identify barriers to conversion and create designs that guide visitors more effectively toward your goals." },
    ],
    relatedServices: ["website-development"],
  },

  "pitch-deck-corporate-decks": {
    hero: {
      headline: "Pitch Deck & Corporate Decks that communicate value clearly",
      subheadline: "Custom investor and corporate decks designed to communicate value clearly",
      supportingText: "Based on 500+ successful decks & 12 years of presentation design expertise",
      ctaText: "BOOK A CALL",
      ctaLink: "https://calendly.com/webfudgeagency",
    },
    stats: {
      projects: "500+",
      decks: "1K+",
      fundsRaised: "$100M+",
      clientSatisfaction: "98%",
      turnaround: "2 weeks",
    },
    challenges: [
      { id: 1, title: "Weak investor presentations", description: "Generic or poorly designed pitch decks fail to capture investor attention. Professional deck design clarifies your story and differentiates you in competitive fundraising.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 2, title: "Inconsistent corporate materials", description: "Inconsistent presentation design across teams weakens your brand. We create cohesive deck templates and guidelines for consistent, professional communication.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 3, title: "Data-heavy slides that confuse", description: "Dense, unclear data visualisation loses your audience. We transform complex information into clear, compelling visuals that support your narrative.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 4, title: "Outdated design and narrative", description: "Outdated deck design and structure can undermine your credibility. We modernize content and design so your story lands with impact.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 5, title: "No clear narrative arc", description: "Decks that jump between topics lose the audience. We structure your deck with a clear narrative that builds to a compelling ask.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
      { id: 6, title: "Time-consuming in-house design", description: "Creating investor-grade decks in-house is time-consuming. We deliver polished, on-brand decks so you can focus on fundraising and execution.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
    ],
    process: [
      { step: 1, title: "Brief & Story Outline", description: "We align on your narrative, key messages, and audience. We outline the deck structure and flow so every slide supports your story and ask." },
      { step: 2, title: "Content & Data Visualisation", description: "We turn your content and data into clear, impactful visuals. We design charts, tables, and diagrams that are easy to scan and remember." },
      { step: 3, title: "Design & Visual Refinement", description: "We apply a consistent visual system—typography, color, imagery—so the deck feels professional and on-brand. We refine based on your feedback." },
      { step: 4, title: "Speaker Notes & Handouts", description: "We add speaker notes and prepare handout or PDF versions as needed, so you can present and share the deck with confidence." },
      { step: 5, title: "Delivery & Revisions", description: "We deliver final files in the formats you need (PPT, Keynote, PDF) and support a round of revisions so the deck is pitch-ready." },
    ],
    reasons: [
      { id: 1, title: "Investor-ready design", description: "We design decks that meet the expectations of investors and boards, with clear narrative and professional visuals.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
      { id: 2, title: "Data visualisation expertise", description: "We turn complex data into clear charts and visuals that support your story and make key points memorable.", icon: "https://cdn.lordicon.com/rpviwvwn.json" },
      { id: 3, title: "Consistent brand application", description: "We apply your brand guidelines across every slide so your deck reinforces your identity and credibility.", icon: "https://cdn.lordicon.com/exymduqj.json" },
      { id: 4, title: "Fast turnaround", description: "We work to your timeline so you can hit fundraising and presentation deadlines without sacrificing quality.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 5, title: "Narrative and structure", description: "We focus on story and flow, not just aesthetics, so your deck builds to a clear, compelling ask.", icon: "https://cdn.lordicon.com/lbcxnxti.json" },
      { id: 6, title: "Multiple formats", description: "We deliver in PowerPoint, Keynote, and PDF, with speaker notes and handout versions as needed.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
    ],
    faqs: [
      { id: 1, question: "What's included in a pitch deck design?", answer: "We typically include a full deck structure, slide design, data visualisation, and narrative flow. We can work from your outline or help you develop the story from scratch. Final files are delivered in your preferred format (PPT, Keynote, PDF)." },
      { id: 2, question: "How long does a pitch deck project take?", answer: "Timelines vary with scope. A standard investor deck often takes 2–3 weeks from brief to final delivery. We can accommodate faster turnarounds when needed." },
      { id: 3, question: "Can you work with our existing deck?", answer: "Yes. We can redesign an existing deck, improve narrative and data slides, and align the design with your brand." },
      { id: 4, question: "Do you design for both pitch and corporate decks?", answer: "Yes. We design investor pitch decks, board decks, sales decks, and internal corporate presentations. We adapt structure and tone to the audience and goal." },
      { id: 5, question: "What if we need last-minute changes?", answer: "We include a round of revisions in our process and can accommodate urgent changes when possible. For ongoing needs, we can discuss retainer support." },
      { id: 6, question: "Will the deck match our brand?", answer: "We use your brand guidelines—colors, fonts, logo—so the deck is consistent with your other materials and reinforces your brand." },
    ],
    relatedServices: ["pitch-deck-design", "corporate-presentations"],
  },

  "e-commerce-development": {
    hero: {
      headline: "E-commerce Development that drives sales and grows your online business",
      subheadline: "Powerful online stores built for conversion and scalability",
      supportingText: "Based on 500+ successful e-commerce projects & 12 years of online retail expertise",
      ctaText: "BOOK A CALL",
      ctaLink: "https://calendly.com/webfudgeagency",
    },
    stats: {
      projects: "500+",
      conversionRate: "3.5%",
      revenue: "$50M+",
      loadSpeed: "<2s",
      mobileOptimized: "100%",
      clientSatisfaction: "98%",
    },
    challenges: [
      { id: 1, title: "Low conversion rates", description: "Poorly designed checkout processes and confusing navigation lead to abandoned carts. We build e-commerce sites optimized for conversion with streamlined checkout and clear product presentation.", icon: "https://cdn.lordicon.com/slkvcfos.json" },
      { id: 2, title: "Limited payment options", description: "Limited payment methods can lose sales. We integrate multiple payment gateways and options to give customers flexibility and increase conversion rates.", icon: "https://cdn.lordicon.com/gqzfzudq.json" },
      { id: 3, title: "Poor mobile shopping experience", description: "E-commerce sites that don't work well on mobile lose significant sales. We build mobile-optimized stores that provide excellent shopping experiences on all devices.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 4, title: "Inventory management complexity", description: "Managing inventory, orders, and products across multiple channels is challenging. We build or integrate systems that streamline inventory management and order processing.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 5, title: "Slow page load times", description: "Slow-loading product pages and checkout processes drive customers away. We optimize for speed, ensuring fast load times that keep customers engaged.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 6, title: "Limited scalability", description: "E-commerce platforms that can't handle growth limit your business potential. We build scalable solutions that can grow with your business and handle traffic spikes.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
    ],
    process: [
      { step: 1, title: "E-commerce Strategy & Planning", description: "We analyze your products, target market, and business goals to define the e-commerce strategy. We select the best platform (Shopify, WooCommerce, or custom) and plan features that will drive sales." },
      { step: 2, title: "Design & User Experience", description: "We design intuitive product pages, shopping carts, and checkout flows optimized for conversion. Every element is designed to guide customers toward purchase while providing an excellent shopping experience." },
      { step: 3, title: "Development & Integration", description: "We build your online store, integrate payment gateways, shipping providers, inventory systems, and third-party tools. We ensure all features work seamlessly together." },
      { step: 4, title: "Product Setup & Configuration", description: "We set up your product catalog, configure shipping options, tax settings, and payment methods. We ensure your store is ready to accept orders and process transactions." },
      { step: 5, title: "Testing & Launch", description: "We thoroughly test all functionality including checkout, payments, inventory, and integrations. We handle launch procedures and provide training to ensure your team can manage the store effectively." },
    ],
    reasons: [
      { id: 1, title: "Conversion-optimized design", description: "We design every element with conversion in mind—from product pages to checkout—creating a shopping experience that guides customers to purchase and maximizes sales.", icon: "https://cdn.lordicon.com/ijsqrapz.json" },
      { id: 2, title: "Multiple platform expertise", description: "We're experts in Shopify, WooCommerce, and custom e-commerce development, selecting the best platform for your specific needs, budget, and growth plans.", icon: "https://cdn.lordicon.com/slkvcfos.json" },
      { id: 3, title: "Payment & shipping integration", description: "We integrate multiple payment gateways and shipping providers, giving customers flexibility and ensuring smooth order processing and fulfillment.", icon: "https://cdn.lordicon.com/gqzfzudq.json" },
      { id: 4, title: "Mobile-optimized shopping", description: "We build mobile-first e-commerce experiences that make shopping easy on any device, capturing the growing mobile commerce market.", icon: "https://cdn.lordicon.com/uisoczqi.json" },
      { id: 5, title: "Scalable architecture", description: "We build e-commerce solutions that can scale with your business, handling increased traffic, products, and orders as you grow.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
      { id: 6, title: "Ongoing support & optimization", description: "We provide ongoing support, updates, and optimization to ensure your store continues to perform well and adapt to changing market needs.", icon: "https://cdn.lordicon.com/lewtedlh.json" },
    ],
    faqs: [
      { id: 1, question: "Which e-commerce platform should I choose?", answer: "The best platform depends on your needs. Shopify is great for quick setup and ease of use. WooCommerce offers more customization for WordPress users. Custom solutions provide maximum flexibility. We'll recommend the best option based on your requirements." },
      { id: 2, question: "How long does an e-commerce development project take?", answer: "Timelines vary based on platform and complexity. A Shopify store might take 4-6 weeks, while a custom e-commerce solution could take 8-12 weeks or more. We'll provide a detailed timeline during our consultation." },
      { id: 3, question: "Can you integrate with our existing systems?", answer: "Yes! We can integrate your e-commerce store with inventory management systems, ERPs, CRMs, email marketing tools, accounting software, and more. We ensure seamless data flow across your business systems." },
      { id: 4, question: "What payment methods can you integrate?", answer: "We can integrate various payment gateways including Stripe, PayPal, Square, Authorize.Net, and many others. We'll set up the payment methods that work best for your business and customers." },
      { id: 5, question: "Will my store be mobile-responsive?", answer: "Absolutely! All e-commerce stores we build are fully responsive and mobile-optimized. We ensure your store provides an excellent shopping experience on desktop, tablet, and mobile devices." },
      { id: 6, question: "Do you provide training and ongoing support?", answer: "Yes! We provide comprehensive training on managing products, orders, and store settings. We also offer ongoing support packages for updates, maintenance, and optimization." },
    ],
    relatedServices: ["ecommerce-development"],
  },
};
